#!/bin/bash
set -e
dropdb --if-exists koschei
createdb koschei
curl https://infrastructure.fedoraproject.org/infra/db-dumps/koschei.dump.xz \
    | unxz | psql koschei
./admin.py alembic upgrade head
