#!/bin/sh
# -*- coding: utf-8 -*-
# Copyright (C) 2017 Red Hat, Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#
# Author: Mikolaj Izdebski <mizdebsk@redhat.com>

# Purpose: run validators on HTML generated by frontend
# Usage:
#  1. run koschei frontend on port 5000, eg. in vagrant:
#    vagrant up
#  2. install HTML validators:
#    dnf copr enable mizdebsk/html-validator
#    dnf install vnu bootlint
#  3. run the script
#    ./aux/validate-html.sh

set -e

work_dir=./lint
base_url=http://127.0.0.1:5000/

rm -rf "${work_dir}/"
mkdir "${work_dir}"


function get()
{
    echo Fetching $1...
    curl -s -L -c /dev/null "${base_url}/${2}" >"${work_dir}/${1}"
}

get add-packages.html 'add-packages?username=vagrant'
get affected-by.html 'affected-by/ant-junit?release1=5.fc27&version1=1.10.1&version2=1.10.1&release2=6.fc27&collection=f27&epoch2=0&epoch1=0'
get build-detail.html 'build/2776006'
get collection-detail.html 'collection/epel7'
get delete-group.html 'groups/eclipse/delete'
get documentation.html 'documentation'
get edit-group.html 'groups/eclipse/edit'
get group-detail.html 'groups/eclipse?collection=f27'
get list-collections.html 'collections'
get list-groups.html 'groups'
get list-packages.html 'packages?collection=epel7'
get list-rebuild-requests.html 'rebuild-request/user/vagrant'
get package-detail.html 'package/nekohtml?collection=f27'
get rebuild-request-detail.html 'rebuild-request/1'
get search-results.html 'search?q=maven'
get stats.html 'stats'
get user-packages.html 'user/vagrant'


# HTML5 validator - https://validator.nu/
# https://github.com/validator/validator/
vnu "${work_dir}"/*


# bootlint - linter for Bootstrap
# https://github.com/twbs/bootlint
bootlint -d W001,W002,W003,W009,W012 "${work_dir}"/*
# disabled warnings - https://github.com/twbs/bootlint/wiki
#  W001 - UTF-8 charset - not needed, server sends proper Content-Type
#  W002 - compatibility with legacy versions of M$ IE - couldn't care less
#  W003 - non-responsive webpage - we are far from reaching that
#  W009 - empty spacer column - sometimes there's simply no content to display...
#  W012 - navbar missing inner container - not needed in Bootstrap 4
