"""Index for koji_task

Revision ID: 142da5a07bc
Revises: 3869a1748e08
Create Date: 2014-11-04 14:00:45.181142

"""

# revision identifiers, used by Alembic.
revision = '142da5a07bc'
down_revision = '3869a1748e08'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(u'ix_koji_task_build_id', 'koji_task', ['build_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(u'ix_koji_task_build_id', table_name='koji_task')
    ### end Alembic commands ###
