"""Compute package state on the fly

Revision ID: 1867c701b
Revises: 585bbd75f3bc
Create Date: 2014-09-10 11:17:50.091169

"""

# revision identifiers, used by Alembic.
revision = '1867c701b'
down_revision = '585bbd75f3bc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    op.add_column('package', sa.Column('ignored', sa.Boolean(), server_default='false', nullable=False))
    op.execute("""UPDATE package SET ignored = TRUE WHERE package.state = 2 OR package.state = 3""")
    op.drop_column('package', u'state')


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('package', sa.Column(u'state', sa.INTEGER(), server_default=u'0', nullable=False))
    op.drop_column('package', 'ignored')
    ### end Alembic commands ###
