"""Add denormalized fields to package

Revision ID: 195b4306b2e
Revises: 42ad047fd7ff
Create Date: 2014-10-17 13:23:33.601567

"""

# revision identifiers, used by Alembic.
revision = '195b4306b2e'
down_revision = '42ad047fd7ff'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('package', sa.Column('last_complete_build_id', sa.Integer(), nullable=True))
    op.add_column('package', sa.Column('resolved', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('package', 'resolved')
    op.drop_column('package', 'last_complete_build_id')
    ### end Alembic commands ###
