"""Add Package.scheduler_skip_reason

Revision ID: 1cf99f3c1f74
Revises: 4f0081f9226f
Create Date: 2016-03-01 13:32:23.996255

"""

# revision identifiers, used by Alembic.
revision = '1cf99f3c1f74'
down_revision = '4f0081f9226f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('package', sa.Column('scheduler_skip_reason', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('package', 'scheduler_skip_reason')
    ### end Alembic commands ###
