"""Make user.email nullable

Revision ID: 1e18cb9177ed
Revises: 2c84d6f01e8c
Create Date: 2015-04-27 18:17:17.946693

"""

# revision identifiers, used by Alembic.
revision = '1e18cb9177ed'
down_revision = '2c84d6f01e8c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    ### end Alembic commands ###
