"""Add repo_id to resolution result

Revision ID: 2144a94d8b4b
Revises: 31590b2e5f0a
Create Date: 2014-07-30 10:59:46.542453

"""

# revision identifiers, used by Alembic.
revision = '2144a94d8b4b'
down_revision = '31590b2e5f0a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resolution_result', sa.Column('repo_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resolution_result', 'repo_id')
    ### end Alembic commands ###
