"""Drop collection arch fields

Revision ID: 2176056cfb43
Revises: 4852a7975500
Create Date: 2016-05-23 10:55:31.312052

"""

# revision identifiers, used by Alembic.
revision = '2176056cfb43'
down_revision = '4852a7975500'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('collection', 'resolution_arches')
    op.drop_column('collection', 'resolve_for_arch')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collection', sa.Column('resolve_for_arch', sa.VARCHAR(), server_default=sa.text(u"'x86_64'::character varying"), autoincrement=False, nullable=False))
    op.add_column('collection', sa.Column('resolution_arches', sa.VARCHAR(), server_default=sa.text(u"'x86_64,i386'::character varying"), autoincrement=False, nullable=False))
    ### end Alembic commands ###
