"""Add buildroot_problem table

Revision ID: 236df7dfaf3d
Revises: 45c6ca63548c
Create Date: 2015-05-21 16:00:12.953298

"""

# revision identifiers, used by Alembic.
revision = '236df7dfaf3d'
down_revision = '45c6ca63548c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buildroot_problem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repo_id', sa.Integer(), nullable=True),
    sa.Column('problem', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['repo_id'], [u'repo.repo_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_buildroot_problem_repo_id', 'buildroot_problem', ['repo_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_buildroot_problem_repo_id', table_name='buildroot_problem')
    op.drop_table('buildroot_problem')
    ### end Alembic commands ###
