"""Cached value for current priority

Revision ID: 260dfbee9be1
Revises: 4d1820f32ac9
Create Date: 2014-11-25 17:32:29.276122

"""

# revision identifiers, used by Alembic.
revision = '260dfbee9be1'
down_revision = '4d1820f32ac9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('package', sa.Column('current_priority', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('package', 'current_priority')
    ### end Alembic commands ###
