"""Add repo_id column to build

Revision ID: 2c9d7b6afc9b
Revises: 413dff986632
Create Date: 2014-08-25 18:46:32.239641

"""

# revision identifiers, used by Alembic.
revision = '2c9d7b6afc9b'
down_revision = '413dff986632'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('build', sa.Column('repo_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('build', 'repo_id')
    ### end Alembic commands ###
