"""Add builroot_diff

Revision ID: 2cd60d55e403
Revises: 39edf88c532a
Create Date: 2014-07-10 19:10:22.542602

"""

# revision identifiers, used by Alembic.
revision = '2cd60d55e403'
down_revision = '39edf88c532a'

from alembic import op
import sqlalchemy as sa

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buildroot_diff',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prev_build_id', sa.Integer(), nullable=True),
    sa.Column('curr_build_id', sa.Integer(), nullable=True),
    sa.Column('arch', sa.String(), nullable=True),
    sa.Column('added', sa.String(), nullable=True),
    sa.Column('removed', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['curr_build_id'], ['build.id'], ),
    sa.ForeignKeyConstraint(['prev_build_id'], ['build.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###

def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('buildroot_diff')
    ### end Alembic commands ###
