"""Unique task_id

Revision ID: 2d07429daa10
Revises: ab659dbe41b
Create Date: 2014-10-24 17:04:50.791262

"""

# revision identifiers, used by Alembic.
revision = '2d07429daa10'
down_revision = 'ab659dbe41b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    op.create_index(u'ix_build_task_id', 'build', ['task_id'], unique=True)
    op.create_unique_constraint('build_task_id_key', 'build', ['task_id'])


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(u'ix_build_task_id', table_name='build')
    ### end Alembic commands ###
