"""Replace dependency weight with distance

Revision ID: 34641b5a09a3
Revises: 403ac9cde8bc
Create Date: 2014-07-17 13:02:25.054621

"""

# revision identifiers, used by Alembic.
revision = '34641b5a09a3'
down_revision = '403ac9cde8bc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dependency_change', sa.Column('distance', sa.Integer(), nullable=True))
    op.drop_column('dependency_change', u'weight')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dependency_change', sa.Column(u'weight', sa.INTEGER(), nullable=True))
    op.drop_column('dependency_change', 'distance')
    ### end Alembic commands ###
