"""Drop unused user fields

Revision ID: 37de714441fd
Revises: 1fb16842dd32
Create Date: 2016-04-21 17:38:47.021422

"""

# revision identifiers, used by Alembic.
revision = '37de714441fd'
down_revision = '1fb16842dd32'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'timezone')
    op.drop_column('user', 'packages_retrieved')
    op.drop_column('user', 'email')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('packages_retrieved', sa.BOOLEAN(), server_default=sa.text(u'false'), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('timezone', sa.VARCHAR(), autoincrement=False, nullable=True))
    ### end Alembic commands ###
