"""Update resolved state manually

Revision ID: 40b065559e29
Revises: 2d07429daa10
Create Date: 2014-10-27 18:46:58.822109

"""

# revision identifiers, used by Alembic.
revision = '40b065559e29'
down_revision = '2d07429daa10'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.execute("""DROP TRIGGER update_resolved_trigger ON resolution_result;
                    DROP FUNCTION update_resolved();""")
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
