"""Add repo_generation_request table

Revision ID: 413dff986632
Revises: 440220ea1db1
Create Date: 2014-08-24 22:30:07.063905

"""

# revision identifiers, used by Alembic.
revision = '413dff986632'
down_revision = '440220ea1db1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repo_generation_request',
    sa.Column('repo_id', sa.Integer(), nullable=False),
    sa.Column('requested', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('repo_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('repo_generation_request')
    ### end Alembic commands ###
