"""Add koji_task table

Revision ID: 440220ea1db1
Revises: 155bedecdab
Create Date: 2014-08-16 17:03:09.675320

"""

# revision identifiers, used by Alembic.
revision = '440220ea1db1'
down_revision = '155bedecdab'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('koji_task',
    sa.Column('build_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('arch', sa.String(length=16), nullable=True),
    sa.Column('state', sa.Integer(), nullable=True),
    sa.Column('started', sa.DateTime(), nullable=True),
    sa.Column('finished', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['build_id'], ['build.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('task_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('koji_task')
    ### end Alembic commands ###
