"""Add user package relation

Revision ID: 4552a3543a68
Revises: 1d3bd1ceb2d5
Create Date: 2015-04-27 12:49:11.445992

"""

# revision identifiers, used by Alembic.
revision = '4552a3543a68'
down_revision = '1d3bd1ceb2d5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_package_relation',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('package_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['package_id'], ['package.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'package_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_package_relation')
    ### end Alembic commands ###
