"""Add repo.base_resolved

Revision ID: 45c6ca63548c
Revises: 1e18cb9177ed
Create Date: 2015-05-21 15:10:55.596947

"""

# revision identifiers, used by Alembic.
revision = '45c6ca63548c'
down_revision = '1e18cb9177ed'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repo', sa.Column('base_resolved', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repo', 'base_resolved')
    ### end Alembic commands ###
