"""Drop user_package_relation

Revision ID: 46698682c9a0
Revises: 49889794b4d7
Create Date: 2016-03-15 14:36:35.627011

"""

# revision identifiers, used by Alembic.
revision = '46698682c9a0'
down_revision = '49889794b4d7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_package_relation')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_package_relation',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('package_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['package_id'], [u'package.id'], name=u'user_package_relation_package_id_fkey', ondelete=u'CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], [u'user.id'], name=u'user_package_relation_user_id_fkey', ondelete=u'CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'package_id', name=u'user_package_relation_pkey')
    )
    ### end Alembic commands ###
