"""Add ON DELETE SET NULL to package.last_build_id

Revision ID: 4926285d0b76
Revises: 2914ccf886ef
Create Date: 2016-01-27 15:37:07.029321

"""

# revision identifiers, used by Alembic.
revision = '4926285d0b76'
down_revision = '2914ccf886ef'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'fkey_package_last_build_id', 'package', type_='foreignkey')
    op.create_foreign_key('fkey_package_last_build_id', 'package', 'build', ['last_build_id'], ['id'], ondelete='SET NULL', use_alter=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fkey_package_last_build_id', 'package', type_='foreignkey')
    op.create_foreign_key(u'fkey_package_last_build_id', 'package', 'build', ['last_build_id'], ['id'])
    ### end Alembic commands ###
