"""Add sorted index on build.package_id

Revision ID: 49f4b34c2712
Revises: 1a1fdbad1017
Create Date: 2014-10-20 10:14:17.778321

"""

# revision identifiers, used by Alembic.
revision = '49f4b34c2712'
down_revision = '1a1fdbad1017'

from alembic import op
import sqlalchemy as sa


def upgrade():
    op.execute('CREATE INDEX build_package_id_ordered ON build(package_id ASC)')

def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('build_package_id_ordered', table_name='build')
    ### end Alembic commands ###
