"""Store package.last_resolution_id

Revision ID: 4d1820f32ac9
Revises: 142da5a07bc
Create Date: 2014-11-04 14:33:52.743202

"""

# revision identifiers, used by Alembic.
revision = '4d1820f32ac9'
down_revision = '142da5a07bc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('package', sa.Column('last_resolution_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('package', 'last_resolution_id')
    ### end Alembic commands ###
