"""Add package_group table

Revision ID: 4db3e31c9b96
Revises: 2cd60d55e403
Create Date: 2014-07-10 20:18:44.741425

"""

# revision identifiers, used by Alembic.
revision = '4db3e31c9b96'
down_revision = '2cd60d55e403'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('package_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('package_group_relation',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('package_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['package_group.id'], ),
    sa.ForeignKeyConstraint(['package_id'], ['package.id'], ),
    sa.PrimaryKeyConstraint('group_id', 'package_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('package_group_relation')
    op.drop_table('package_group')
    ### end Alembic commands ###
