"""Add partial index for running builds

Revision ID: 4f0081f9226f
Revises: 5ac6e922818a
Create Date: 2016-02-29 15:20:02.818722

"""

# revision identifiers, used by Alembic.
revision = '4f0081f9226f'
down_revision = '5ac6e922818a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_build_running', 'build', ['package_id'], unique=True, postgresql_where=sa.text(u'build.state = 2'))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_build_running', table_name='build')
    ### end Alembic commands ###
