"""Make repo.base_resolved non-nullable

Revision ID: 4feeaaf796ad
Revises: 457551e5c8ab
Create Date: 2015-08-17 15:07:26.100469

"""

# revision identifiers, used by Alembic.
revision = '4feeaaf796ad'
down_revision = '457551e5c8ab'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('repo', 'base_resolved',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('repo', 'base_resolved',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    ### end Alembic commands ###
