"""Add more fields to collection

Revision ID: 515f0581e6f7
Revises: 5de968d3311
Create Date: 2016-03-10 10:19:31.544732

"""

# revision identifiers, used by Alembic.
revision = '515f0581e6f7'
down_revision = '5de968d3311'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collection', sa.Column('build_group', sa.String(), server_default='build', nullable=False))
    op.add_column('collection', sa.Column('order', sa.Integer(), server_default='100', nullable=False))
    op.add_column('collection', sa.Column('resolution_arches', sa.String(), server_default='x86_64,i386', nullable=False))
    op.add_column('collection', sa.Column('resolve_for_arch', sa.String(), server_default='x86_64', nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('collection', 'resolve_for_arch')
    op.drop_column('collection', 'resolution_arches')
    op.drop_column('collection', 'order')
    op.drop_column('collection', 'build_group')
    ### end Alembic commands ###
