"""Better composite key for build

Revision ID: 538a778fcd5d
Revises: c6ec45be136
Create Date: 2015-03-02 15:39:11.143170

"""

# revision identifiers, used by Alembic.
revision = '538a778fcd5d'
down_revision = 'c6ec45be136'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE INDEX ix_build_composite ON build(package_id, task_id DESC)')
    op.drop_index('build_package_id_ordered', table_name='build')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('build_package_id_ordered', 'build', ['package_id'], unique=False)
    op.drop_index('ix_build_composite', table_name='build')
    ### end Alembic commands ###
