"""Add repo_mapping

Revision ID: 5992b944544b
Revises: 21bcf7db927c
Create Date: 2016-03-24 11:16:01.916573

"""

# revision identifiers, used by Alembic.
revision = '5992b944544b'
down_revision = '21bcf7db927c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repo_mapping',
    sa.Column('secondary_id', sa.Integer(), nullable=False),
    sa.Column('primary_id', sa.Integer(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('secondary_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('repo_mapping')
    ### end Alembic commands ###
