"""Add index in collection_id

Revision ID: 5de968d3311
Revises: 2946d55e18d
Create Date: 2016-03-02 11:03:30.648877

"""

# revision identifiers, used by Alembic.
revision = '5de968d3311'
down_revision = '2946d55e18d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_package_collection_id', 'package', ['collection_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_package_collection_id', table_name='package')
    ### end Alembic commands ###
