"""Remove logs_downloaded column

Revision ID: a0da55358f4
Revises: 42ec52bcb3b4
Create Date: 2014-08-28 13:49:36.227212

"""

# revision identifiers, used by Alembic.
revision = 'a0da55358f4'
down_revision = '42ec52bcb3b4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('build', u'logs_downloaded')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('build', sa.Column(u'logs_downloaded', sa.BOOLEAN(), nullable=False))
    ### end Alembic commands ###
