"""Index on dependency_change.package_id

Revision ID: c6ec45be136
Revises: 5576cfc14700
Create Date: 2015-02-23 16:24:25.142034

"""

# revision identifiers, used by Alembic.
revision = 'c6ec45be136'
down_revision = '5576cfc14700'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_dependency_change_applied_in_id', 'dependency_change', ['applied_in_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_dependency_change_applied_in_id', table_name='dependency_change')
    ### end Alembic commands ###
